directories:
  "app/helpers":
    UtilityFunction:
      enabled: false

exclude_paths:
  - db/migrate/*.rb
  - app/channels/application_cable/channel.rb
  - app/channels/application_cable/connection.rb
  - app/controllers/application_controller.rb
  - app/helpers/devise_helper.rb
  - config/application.rb
  - config/initializers/devise.rb
  - app/jobs/application_job.rb
  - app/mailers/application_mailer.rb
  - app/models/application_record.rb
