require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/schema.rb
    - node_modules/**/*
    - app/misc/**/*
    - public/**/*
    - vendor/**/*
inherit_gem:
  rubocop-shopify: rubocop.yml
